[tools]
java = "11"

[settings]
env_shell_expand = true

[env]
ANDROID_HOME = "/opt/android-sdk"
ANDROID_CMDLINE_TOOLS_URL = "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
SDKMANAGER = "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager"

[tasks."make:apk"]
depends = ["install:android-sdk"]
run = "./gradlew assembleDebug && echo apk gerado em: app/build/outputs/apk/debug/app-debug.apk"

[tasks."install:android-sdk"]
run = """
#!/bin/bash
has_cmd() { command -v "$1" &>/dev/null; }
has_cmdline_tools() { test -d "${ANDROID_HOME}/cmdline-tools/latest"; }

if ! has_cmdline_tools;
then
    if ! has_cmd wget || ! has_cmd unzip;
    then
        if ! has_cmd apt; then echo "apt unavaliable, please manually install wget, unzip"; exit 1; fi

        sudo apt update
        sudo apt install -y --no-install-recommends wget unzip
    fi

    sudo mkdir -p "${ANDROID_HOME}"
    sudo chown -R $USER:$USER "${ANDROID_HOME}"

    wget "${ANDROID_CMDLINE_TOOLS_URL}" -O /tmp/cmdline-tools.zip
    unzip /tmp/cmdline-tools.zip -d "${ANDROID_HOME}/cmdline-tools"

    mv "${ANDROID_HOME}/cmdline-tools/cmdline-tools" "${ANDROID_HOME}/cmdline-tools/latest"
fi

if ! test -x "${ANDROID_HOME}/platform-tools/adb" || ! test -x "${ANDROID_HOME}/build-tools/34.0.0/aapt2" || ! test -f "${ANDROID_HOME}/platforms/android-34/android.jar";
then
    yes | $SDKMANAGER --sdk_root="${ANDROID_HOME}" "platform-tools" "build-tools;34.0.0" "platforms;android-34"
    yes | $SDKMANAGER --licenses
fi

# cleanup
if test -f /tmp/cmdline-tools.zip;
then
    rm /tmp/cmdline-tools.zip
fi

echo "=== Android SDK =============="
${ANDROID_HOME}/platform-tools/adb --version
${ANDROID_HOME}/build-tools/34.0.0/aapt2 version
echo "=============================="
"""
